// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0xO9Fq4TMuw-fCYrLRXHhX2SZ6ihbvso',
    appId: '1:136165045218:web:623d2daecc8eaf1311bfbb',
    messagingSenderId: '136165045218',
    projectId: 'grmc-386010',
    authDomain: 'grmc-386010.firebaseapp.com',
    storageBucket: 'grmc-386010.appspot.com',
    measurementId: 'G-CSEHEDHBR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDevjHd-cIaP8yUdkVUbTuz_8SgIuQXPRY',
    appId: '1:136165045218:android:9fde27afe4d16bfe11bfbb',
    messagingSenderId: '136165045218',
    projectId: 'grmc-386010',
    storageBucket: 'grmc-386010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAIzQ4dZZQnNelE8ra93gB_dyS_V7tX74',
    appId: '1:136165045218:ios:f79a9ec0d5c818ff11bfbb',
    messagingSenderId: '136165045218',
    projectId: 'grmc-386010',
    storageBucket: 'grmc-386010.appspot.com',
    iosClientId: '136165045218-itc44llnm3clnm99vplh8ib7cjsvmrss.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSocialLoginSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAIzQ4dZZQnNelE8ra93gB_dyS_V7tX74',
    appId: '1:136165045218:ios:f79a9ec0d5c818ff11bfbb',
    messagingSenderId: '136165045218',
    projectId: 'grmc-386010',
    storageBucket: 'grmc-386010.appspot.com',
    iosClientId: '136165045218-itc44llnm3clnm99vplh8ib7cjsvmrss.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSocialLoginSample',
  );
}
